[workspace]
resolver = "2"
members = ["xtask", "crates/*"]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Busticated <itsbusticated@gmail.com>"]
repository = "https://github.com/busticated/rusty"

[profile.dev]
# Faster builds, disable if you need
debug = 0
