[package]
name = "detect-newline-style"
description = "Determine a string's preferred newline character"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
regex = "1.*"
