name: Run CI/CD Jobs

on:
  push:
    paths:
      - ".github/workflows/**.yml"
      - "**/Cargo.toml"
      - "**.rs"
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/test.yaml
    secrets: inherit

