name: Test

on:
  workflow_call:

jobs:
  test:
    name: Rust for ${{ matrix.architecture }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      # fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        architecture:
          - x64
    steps:
      - name: Git Symlink Setup for Windows
        if: matrix.os == 'windows-latest'
        run: git config --global core.symlinks true
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Install Rust Toolchain (stable)
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Project
        run: cargo xtask setup
      - name: Run Tests & Coverage
        run: cargo xtask ci

